### ISSUE TITLE
Import Errors

### ISSUE THREAD

**Issue by vdhanraj** [google-research/google-research#1855]
Hi, 

I'm running into some import errors when trying to run the 00_check_data notebook in colab. When importing kws_streaming.models import models, I get an error saying module 'keras._tf_keras.keras.layers' has no attribute 'LocallyConnected1D'.

I've followed the instructions on kws_experiments_paper_12_labels.md to install the packages that should be required to run the code, but it still isn't working. The .md file specifies that the code worked on tf_nightly-2.3.0.dev20200515-cp36-cp36m-manylinux2010_x86_64.whl, but tf_nightly doesn't have that version available to download via pip anymore, so I'm not sure how to obtain it. Does anyone know what I need to install to get this code working?

**Comment by rybakov** [comment]
kws lib does not use or import LocallyConnected1D explicitly (full log can be helpful to see where the error happened).
kws lib is at sync with HEAD of TF, so please try tf_nightly.

**Comment by vdhanraj** [comment]
Hi @rybakov,

I'm currently using tf-nightly (tf-nightly==2.16.0.dev20231209), is this an acceptable version of tf-nightly?

Here's the full error log: 
[3](vscode-notebook-cell:/home/vdhanraj/Desktop/kws_streaming/colab/00_check_data.ipynb#W5sZmlsZQ%3D%3D?line=2) import logging
      [4](vscode-notebook-cell:/home/vdhanraj/Desktop/kws_streaming/colab/00_check_data.ipynb#W5sZmlsZQ%3D%3D?line=3) from kws_streaming.models import model_flags
----> [5](vscode-notebook-cell:/home/vdhanraj/Desktop/kws_streaming/colab/00_check_data.ipynb#W5sZmlsZQ%3D%3D?line=4) from kws_streaming.models import models
      [6](vscode-notebook-cell:/home/vdhanraj/Desktop/kws_streaming/colab/00_check_data.ipynb#W5sZmlsZQ%3D%3D?line=5) from kws_streaming.layers.modes import Modes
      [7](vscode-notebook-cell:/home/vdhanraj/Desktop/kws_streaming/colab/00_check_data.ipynb#W5sZmlsZQ%3D%3D?line=6) from kws_streaming.train import test

File [~/Desktop/kws_streaming/colab/./google-research/kws_streaming/models/models.py:17](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/Desktop/kws_streaming/colab/google-research/kws_streaming/models/models.py:17)
      [1](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/Desktop/kws_streaming/colab/google-research/kws_streaming/models/models.py:1) # coding=utf-8
      [2](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/Desktop/kws_streaming/colab/google-research/kws_streaming/models/models.py:2) # Copyright 2023 The Google Research Authors.
      [3](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/Desktop/kws_streaming/colab/google-research/kws_streaming/models/models.py:3) #
   (...)
     [13](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/Desktop/kws_streaming/colab/google-research/kws_streaming/models/models.py:13) # See the License for the specific language governing permissions and
     [14](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/Desktop/kws_streaming/colab/google-research/kws_streaming/models/models.py:14) # limitations under the License.
     [16](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/Desktop/kws_streaming/colab/google-research/kws_streaming/models/models.py:16) """Supported models."""
---> [17](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/Desktop/kws_streaming/colab/google-research/kws_streaming/models/models.py:17) import kws_streaming.models.att_mh_rnn as att_mh_rnn
     [18](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/Desktop/kws_streaming/colab/google-research/kws_streaming/models/models.py:18) import kws_streaming.models.att_rnn as att_rnn
     [19](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/Desktop/kws_streaming/colab/google-research/kws_streaming/models/models.py:19) import kws_streaming.models.bc_resnet as bc_resnet

File [~/Desktop/kws_streaming/colab/./google-research/kws_streaming/models/att_mh_rnn.py:18](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/Desktop/kws_streaming/colab/google-research/kws_streaming/models/att_mh_rnn.py:18)
     [16](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/Desktop/kws_streaming/colab/google-research/kws_streaming/models/att_mh_rnn.py:16) """BiRNN model with multihead attention."""
     [17](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/Desktop/kws_streaming/colab/google-research/kws_streaming/models/att_mh_rnn.py:17) from kws_streaming.layers import modes
---> [18](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/Desktop/kws_streaming/colab/google-research/kws_streaming/models/att_mh_rnn.py:18) from kws_streaming.layers import speech_features
     [19](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/Desktop/kws_streaming/colab/google-research/kws_streaming/models/att_mh_rnn.py:19) from kws_streaming.layers.compat import tf
     [20](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/Desktop/kws_streaming/colab/google-research/kws_streaming/models/att_mh_rnn.py:20) import kws_streaming.models.model_utils as utils

File [~/Desktop/kws_streaming/colab/./google-research/kws_streaming/layers/speech_features.py:26](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/Desktop/kws_streaming/colab/google-research/kws_streaming/layers/speech_features.py:26)
     [24](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/Desktop/kws_streaming/colab/google-research/kws_streaming/layers/speech_features.py:24) from kws_streaming.layers import random_shift
     [25](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/Desktop/kws_streaming/colab/google-research/kws_streaming/layers/speech_features.py:25) from kws_streaming.layers import random_stretch_squeeze
---> [26](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/Desktop/kws_streaming/colab/google-research/kws_streaming/layers/speech_features.py:26) from kws_streaming.layers import spectrogram_augment
     [27](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/Desktop/kws_streaming/colab/google-research/kws_streaming/layers/speech_features.py:27) from kws_streaming.layers import spectrogram_cutout
     [28](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/Desktop/kws_streaming/colab/google-research/kws_streaming/layers/speech_features.py:28) from kws_streaming.layers import windowing

File [~/Desktop/kws_streaming/colab/./google-research/kws_streaming/layers/spectrogram_augment.py:20](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/Desktop/kws_streaming/colab/google-research/kws_streaming/layers/spectrogram_augment.py:20)
     [17](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/Desktop/kws_streaming/colab/google-research/kws_streaming/layers/spectrogram_augment.py:17) from typing import Any, Dict
     [19](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/Desktop/kws_streaming/colab/google-research/kws_streaming/layers/spectrogram_augment.py:19) import tensorflow as tf
---> [20](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/Desktop/kws_streaming/colab/google-research/kws_streaming/layers/spectrogram_augment.py:20) import tensorflow_model_optimization as tfmot
     [22](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/Desktop/kws_streaming/colab/google-research/kws_streaming/layers/spectrogram_augment.py:22) from kws_streaming.layers.compat import tf
     [23](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/Desktop/kws_streaming/colab/google-research/kws_streaming/layers/spectrogram_augment.py:23) from tensorflow.python.ops import array_ops  # pylint: disable=g-direct-tensorflow-import

File [~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/__init__.py:86](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/__init__.py:86)
     [82](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/__init__.py:82) # To ensure users only access the expected public API, the API structure is
     [83](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/__init__.py:83) # created in the `api` directory. Import all api modules.
     [84](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/__init__.py:84) from tensorflow_model_optimization.python.core import version
---> [86](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/__init__.py:86) from tensorflow_model_optimization.python.core.api import clustering
     [87](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/__init__.py:87) from tensorflow_model_optimization.python.core.api import experimental
     [88](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/__init__.py:88) from tensorflow_model_optimization.python.core.api import quantization

File [~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/api/__init__.py:16](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/api/__init__.py:16)
      [1](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/api/__init__.py:1) # Copyright 2021 The TensorFlow Authors. All Rights Reserved.
      [2](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/api/__init__.py:2) #
      [3](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/api/__init__.py:3) # Licensed under the Apache License, Version 2.0 (the "License");
   (...)
     [13](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/api/__init__.py:13) # limitations under the License.
     [14](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/api/__init__.py:14) # ==============================================================================
     [15](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/api/__init__.py:15) """Import API modules for Tensorflow Model Optimization."""
---> [16](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/api/__init__.py:16) from tensorflow_model_optimization.python.core.api import clustering
     [17](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/api/__init__.py:17) from tensorflow_model_optimization.python.core.api import experimental
     [18](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/api/__init__.py:18) from tensorflow_model_optimization.python.core.api import quantization

File [~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/api/clustering/__init__.py:16](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/api/clustering/__init__.py:16)
      [1](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/api/clustering/__init__.py:1) # Copyright 2020 The TensorFlow Authors. All Rights Reserved.
      [2](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/api/clustering/__init__.py:2) #
      [3](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/api/clustering/__init__.py:3) # Licensed under the Apache License, Version 2.0 (the "License");
   (...)
     [13](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/api/clustering/__init__.py:13) # limitations under the License.
     [14](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/api/clustering/__init__.py:14) # ==============================================================================
     [15](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/api/clustering/__init__.py:15) """Module containing code for clustering."""
---> [16](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/api/clustering/__init__.py:16) from tensorflow_model_optimization.python.core.api.clustering import keras

File [~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/api/clustering/keras/__init__.py:19](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/api/clustering/keras/__init__.py:19)
     [16](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/api/clustering/keras/__init__.py:16) # pylint: disable=g-bad-import-order
     [17](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/api/clustering/keras/__init__.py:17) from tensorflow_model_optimization.python.core.clustering.keras import experimental
---> [19](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/api/clustering/keras/__init__.py:19) from tensorflow_model_optimization.python.core.clustering.keras.cluster import cluster_scope
     [20](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/api/clustering/keras/__init__.py:20) from tensorflow_model_optimization.python.core.clustering.keras.cluster import cluster_weights
     [21](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/api/clustering/keras/__init__.py:21) from tensorflow_model_optimization.python.core.clustering.keras.cluster import strip_clustering

File [~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/cluster.py:22](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/cluster.py:22)
     [19](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/cluster.py:19) import tensorflow as tf
     [21](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/cluster.py:21) from tensorflow_model_optimization.python.core.clustering.keras import cluster_config
---> [22](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/cluster.py:22) from tensorflow_model_optimization.python.core.clustering.keras import cluster_wrapper
     [23](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/cluster.py:23) from tensorflow_model_optimization.python.core.clustering.keras import clustering_centroids
     [25](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/cluster.py:25) k = tf.keras.backend

File [~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/cluster_wrapper.py:24](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/cluster_wrapper.py:24)
     [22](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/cluster_wrapper.py:22) from tensorflow_model_optimization.python.core.clustering.keras import clusterable_layer
     [23](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/cluster_wrapper.py:23) from tensorflow_model_optimization.python.core.clustering.keras import clustering_centroids
---> [24](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/cluster_wrapper.py:24) from tensorflow_model_optimization.python.core.clustering.keras import clustering_registry
     [26](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/cluster_wrapper.py:26) attrgetter = operator.attrgetter  # pylint: disable=invalid-name
     [27](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/cluster_wrapper.py:27) keras = tf.keras

File [~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:57](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:57)
     [53](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:53)         return ans
     [54](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:54)     return ClusteringAlgorithm
---> [57](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:57) class ClusteringRegistry(object):
     [58](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:58)   """Registry responsible for built-in keras layers."""
     [60](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:60)   # The keys represent built-in keras layers and the values represent the
     [61](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:61)   # the variables within the layers which hold the kernel weights. This
     [62](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:62)   # allows the wrapper to access and modify the weights.

File [~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:76](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:76), in ClusteringRegistry()
     [58](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:58) """Registry responsible for built-in keras layers."""
     [60](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:60) # The keys represent built-in keras layers and the values represent the
     [61](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:61) # the variables within the layers which hold the kernel weights. This
     [62](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:62) # allows the wrapper to access and modify the weights.
     [63](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:63) _LAYERS_WEIGHTS_MAP = {
     [64](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:64)     layers.Conv1D: ['kernel'],
     [65](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:65)     layers.Conv1DTranspose: ['kernel'],
     [66](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:66)     layers.Conv2D: ['kernel'],
     [67](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:67)     layers.Conv2DTranspose: ['kernel'],
     [68](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:68)     layers.Conv3D: ['kernel'],
     [69](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:69)     layers.Conv3DTranspose: ['kernel'],
     [70](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:70)     # non-clusterable due to big unrecoverable accuracy loss
     [71](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:71)     layers.DepthwiseConv2D: [],
     [72](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:72)     layers.SeparableConv1D: ['pointwise_kernel'],
     [73](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:73)     layers.SeparableConv2D: ['pointwise_kernel'],
     [74](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:74)     layers.Dense: ['kernel'],
     [75](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:75)     layers.Embedding: ['embeddings'],
---> [76](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:76)     layers.LocallyConnected1D: ['kernel'],
     [77](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:77)     layers.LocallyConnected2D: ['kernel'],
     [78](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:78)     layers.BatchNormalization: [],
     [79](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:79)     layers.LayerNormalization: [],
     [80](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:80) }
     [82](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:82) _SUPPORTED_RNN_CELLS = frozenset({
     [83](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:83)     # Sometimes v2 RNN will wrap some v1 RNN cells and we need
     [84](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:84)     # to consider this
   (...)
     [92](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:92)     tf.compat.v2.keras.layers.StackedRNNCells,
     [93](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:93) })
     [95](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:95) _SUPPORTED_RNN_LAYERS = frozenset([
     [96](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:96)     layers.GRU,
     [97](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:97)     layers.LSTM,
   (...)
    [100](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:100)     layers.Bidirectional,
    [101](https://file+.vscode-resource.vscode-cdn.net/home/vdhanraj/Desktop/kws_streaming/colab/~/.local/lib/python3.10/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py:101) ])

AttributeError: module 'keras._tf_keras.keras.layers' has no attribute 'LocallyConnected1D'

**Comment by rybakov** [comment]
My guess is that you are using outdated version of tensorflow_model_optimization which is mismatched with tf.
So I would suggest to update [tensorflow_model_optimization](https://www.tensorflow.org/model_optimization/guide/install)

**Comment by vdhanraj** [comment]
Hi @rybakov, thanks for the suggestion. I updated tensorflow_model_optimization, which solved the above issue, but was still running into problems where the code was referencing tf._keras_internal, which doesn't seem to exist. Maybe I'm using a different version of tf_nightly, or something else is out of date, but I've gotten the code to work by either removing or replacing occurrences of tf_keras_internal. Let me know if there is an alternative solution.

**Comment by vdhanraj** [comment]
@rybakov The code is still not working, removing references to internal variables made the code crash at later points in the pipeline. I don't think the code works properly with the current version of tf-nightly, is it possible to update the code so that it is compatible?
