### ISSUE TITLE
Inference code for Streaming Aware neural network models doesn't work with TF2.3

### ISSUE THREAD

**Issue by AakashKumarNain** [google-research/google-research#489]
Thank you for this work. I believe the inference code has been tested on a nightly build and some files like use internal/private ops that aren't available anymore. 

```python
from kws_streaming.models import models
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-0cb1216f5109> in <module>()
----> 1 from kws_streaming.models import models

3 frames
/content/google-research/kws_streaming/layers/random_shift.py in <module>()
     17 
     18 from kws_streaming.layers.compat import tf
---> 19 from tensorflow.python.keras.utils import control_flow_util  # pylint: disable=g-direct-tensorflow-import
     20 from tensorflow.python.ops import array_ops  # pylint: disable=g-direct-tensorflow-import
     21 

ImportError: cannot import name 'control_flow_util'
```

**Comment by rybakov** [comment]
Thank you for evaluating kws_streaming lib! 
Yes, it is tested with tf nightly builds to guarantee compatibility with the latest tf version. Recently there was a refactor in tf.keras, in which 'tf_utils' was replaced by 'control_flow_util'. That is why kws_streaming was evaluated on tf version 2.4.0-dev20200917 as described in [experiments](https://github.com/google-research/google-research/tree/master/kws_streaming/experiments). I would suggest to follow instructions in [experiments](https://github.com/google-research/google-research/tree/master/kws_streaming/experiments), or install tf_nightly.

If you prefer to use tf 2.3, then I would suggest to replace "from tensorflow.python.keras.utils import control_flow_util" by "from tensorflow.python.keras.utils import tf_utils" it should work with older version of tf.

**Comment by AakashKumarNain** [comment]
> Yes, it is tested with tf nightly builds to guarantee compatibility with the latest tf version.

Ahh okay. Git it. That makes sense. Thank you. I will check again with 2.4.rcx and will close this issue if everything goes fine.

**Comment by AakashKumarNain** [comment]
Hi, I switched to 2.4 and most of the code is working but there are some flags that are missing in the inference notebook. When I am loading the weights in these lines:

```python
# create model with flag's parameters
model_non_stream_batch = models.MODELS[flags.model_name](flags)

# load model's weights
weights_name = 'best_weights'
model_non_stream_batch.load_weights(os.path.join(train_dir, weights_name))
```

I am getting this error:

```---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-28-a170e05f648d> in <module>()
      1 # create model with flag's parameters
----> 2 model_non_stream_batch = models.MODELS[flags.model_name](flags)
      3 
      4 # load model's weights
      5 weights_name = 'best_weights'

1 frames
/content/google-research/kws_streaming/models/svdf.py in model(flags)
    104     # it is a self contained model, user need to feed raw audio only
    105     net = speech_features.SpeechFeatures(
--> 106         speech_features.SpeechFeatures.get_params(flags))(
    107             net)
    108 

/content/google-research/kws_streaming/layers/speech_features.py in get_params(flags)
    274     """
    275 
--> 276     if flags.time_shift_ms != 0.0 and flags.sp_time_shift_ms != 0.0:
    277       raise ValueError('both time_shift_ms and sp_time_shift_ms are set '
    278                        'only one parameter should be used: '

AttributeError: 'Namespace' object has no attribute 'sp_time_shift_ms'

```

**Comment by rybakov** [comment]
thank you for reporting it! I will update colab example in couple of days

**Comment by rybakov** [comment]
I fixed colab examples, please update it and let me know if you have any issues.

**Comment by AakashKumarNain** [comment]
Sure. Thanks. Let me try to run it again

**Comment by AakashKumarNain** [comment]
@rybakov I tried it again and now the flag for `wav` is missing. 

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-27-28f17008ce2c> in <module>()
      1 # prepare mapping of index to word
----> 2 audio_processor = data.input_data.AudioProcessor(flags)
      3 index_to_label = {}
      4 # labels used for training
      5 for word in audio_processor.word_to_index.keys():

/content/google-research/kws_streaming/data/input_data.py in __init__(self, flags)
    186   def __init__(self, flags):
    187     wanted_words = flags.wanted_words.split(',')
--> 188     if flags.wav:
    189       file_ext = '*.wav'
    190     else:

AttributeError: 'Namespace' object has no attribute 'wav'
```

**Comment by rybakov** [comment]
I guess you run only inference colab and test models from older example: these models are not compatible any more and have to be re-trained.
Please update all colabs and run them in order:
[00_check_data.ipynb](https://github.com/google-research/google-research/blob/master/kws_streaming/colab/00_check_data.ipynb)
[01_train.ipynb](https://github.com/google-research/google-research/blob/master/kws_streaming/colab/01_train.ipynb)
[02_inference.ipynb](https://github.com/google-research/google-research/blob/master/kws_streaming/colab/02_inference.ipynb)
